dist: trusty
sudo: false
language: cpp
os:
  - linux
compiler:
  - gcc
  #  - clang
cache: packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - gcc-6
      - g++-6
notifications:
  email: false
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#freeboson"
    template:
      - "[%{repository} %{branch}] Build #%{build_number} (%{commit}) : [%{message}]"
    on_success: change
    on_failure: always
    skip_join: true
before_install:
  - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
  - sh cmake-3.7.2-Linux-x86_64.sh --prefix=cmake --skip-license --exclude-subdir
script:
  - mkdir build
  - cd build
  - cmake .. && make
