language: cpp
os:
  - linux
compiler:
  - clang
  - gcc
cache: packages
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - curl-ssl
      - cmake
      - cmake-data
      - gfortran
notifications:
  email: false
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#freeboson"
    template:
      - "[%{repository} %{branch}] Build #%{build_number} (%{commit}) : [%{message}]"
    on_success: change
    on_failure: always
    skip_join: true
script:
  - mkdir build
  - cd build
  - cmake .. && make
